/// File: firebase_options.dart. Contiene codice Dart del progetto.

// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBArZCfVtV3xj_cip0P1QD2bjlkLxV7gmA',
    appId: '1:795290115421:web:9a19df943ddc09d64e1cb4',
    messagingSenderId: '795290115421',
    projectId: 'dartsroses',
    authDomain: 'dartsroses.firebaseapp.com',
    storageBucket: 'dartsroses.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArsQKz2H_-7vN9cIZy8u1rm7qTZkdwwt0',
    appId: '1:795290115421:android:93999c7628660c144e1cb4',
    messagingSenderId: '795290115421',
    projectId: 'dartsroses',
    storageBucket: 'dartsroses.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSs-6CGWn5coVfC-Ffyr4NSflB0JXYjCI',
    appId: '1:795290115421:ios:954073d6ec4cbc9c4e1cb4',
    messagingSenderId: '795290115421',
    projectId: 'dartsroses',
    storageBucket: 'dartsroses.firebasestorage.app',
    iosBundleId: 'com.az.darts',
  );

}